version: '3'
services:
  plnx:
    image: "${IMAGENAME}"
    environment:
        - USER_ID=${IUID}
        - USER_NAME=${whoami}
        - GROUP_ID=${IGID}
        - pVERSION=${VERSION}
        - ARCH=${ARCH}
    volumes: 
        - /opt/Xilinx:/opt/Xilinx
        - /home/${whoami}/workspace:/home/${whoami}/workspace
    working_dir:
        ${LDIR}
